services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=Welcome@123
    ports:
      - 3306:3306
      
  backend:
    build: 
      context: ./elearn-backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 5000:8080
    restart: unless-stopped
  
  frontend:
    build: 
      context: ./elearn-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 2000:80
    restart: unless-stopped